### ISSUE TITLE
supports jpeg, but 'image/png32' is used should only trigger on "photo" category

### ISSUE THREAD

**Issue by andrewharvey** [rbuffat/eli_watchdog#1]
> Warning: Server supports jpeg, but 'image/png32' is used. (Server supports: 'image/bmp', 'image/jpeg', 'image/tiff', 'image/png', 'image/png8', 'image/png24', 'image/png32', 'image/gif', 'image/svg+xml')

This should only trigger when category is `photo` or `historicphoto` other categories like `map` are usually much smaller when served as png.

**Comment by rbuffat** [comment]
I changed the warning to be category dependent, and also adapted the warning that it sounds more like a suggestion: https://github.com/rbuffat/eli_watchdog/commit/138346b8106f3f787989c2a5aad135214991cf11
