### ISSUE TITLE
Update page

### ISSUE THREAD

**Issue by matheusgomesms** [rbuffat/eli_watchdog#74]
Hi René!

Is it possible to update the results from Watchdog? Not sure if it is easy, but right now I see it was last updated on 18 Feb.

Thanks a lot for your work!

**Comment by rbuffat** [comment]
@matheusgomesms Thanks for your comment. I will look into it. I was in the process of rewriting it as the current state of the code is not great but then run out of time.

**Comment by rbuffat** [comment]
The script is up and running again. Thus in the next days there will be a wave of opened github issues of sources that broke during the last past months.

**Comment by matheusgomesms** [comment]
Thanks a lot, René!
